# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

#before_script:
#  - python --version  # For debugging
#  - pip install virtualenv
#  - virtualenv venv
#  - source venv/bin/activate

test:
  script:
    - python --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - python -m build
    - pytest
    #- pip install tox flake8  # you can also use tox
    #- tox -e py36,flake8

run:
  script:
    - python --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - python -m build
    #- python setup.py bdist_wheel
    # an alternative approach is to install and run:
    #- pip install dist/*
    # run the command here
    #- python -m avonic-camera-api
  artifacts:
    paths:
      - dist/*.whl

pages:
  script:
    - python --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install sphinx sphinx-rtd-theme
    - cd doc
    - make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production

git-inspector:
    image: python:2.7.16-alpine3.8
    script: 
        - apk add git
        - git clone https://github.com/ejwa/gitinspector.git
        - cd gitinspector
        - python2 gitinspector.py --format=htmlembedded --grading=true --file-types='py,md,tex' ../ > ../git.html
    artifacts:
      paths:
        - git.html

compile-report:
    image: texlive/texlive:latest
    script:
      - cd docs
      - pdflatex -file-line-error -interaction=nonstopmode -synctex=1 -output-format=pdf final-report.tex
      - exit
    artifacts:
      paths:
        - docs/final-report.pdf
    rules:
      - changes: 
        - "*.tex"
        - "**/*.tex"
