# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest
stages: 
  - build
  - test
  - reports
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/
    
test:
  stage: test
  variables:
    CAM_IP: "0.0.0.0"
    # PORT of Camera
    CAM_PORT: 1259
    # IP address of Microphone
    MIC_IP: "192.168.5.62"
    # PORT of Microphone
    MIC_PORT: 45
    MIC_THRESH: 55
  before_script:
    - apt-get update
    - yes | apt-get install libgl1
  script:
    - python --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install build
    - pip install -e '.[test]'
    - pytest --cov --cov-report xml:cov.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cov.xml
    when: always

pylint:
  stage: test
  image: python:3.10-slim
  before_script:
    - mkdir -p public/badges public/lint
    - echo undefined > public/badges/$CI_JOB_NAME.score
    - pip install pylint-gitlab
  script:
    - pylint --exit-zero --output-format=text $(find -type f -name "*.py" ! -path "**/venv/**") | tee /tmp/pylint.txt
    - sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' /tmp/pylint.txt > public/badges/$CI_JOB_NAME.score
    - pylint --exit-zero --output-format=pylint_gitlab.GitlabCodeClimateReporter $(find -type f -name "*.py" ! -path "**/venv/**") > codeclimate.json
    - pylint --exit-zero --output-format=pylint_gitlab.GitlabPagesHtmlReporter $(find -type f -name "*.py" ! -path "**/venv/**") > public/lint/index.html
  after_script:
    - anybadge --overwrite --label $CI_JOB_NAME --value=$(cat public/badges/$CI_JOB_NAME.score) --file=public/badges/$CI_JOB_NAME.svg 4=red 6=orange 8=yellow 10=green
    - |
      echo "Your score is: $(cat public/badges/$CI_JOB_NAME.score)"
  artifacts:
    paths:
      - public
    reports:
      codequality: codeclimate.json
    when: always

run:
  stage: build
  script:
    - python --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install build
    - python -m build
    - pip install .
  artifacts:
    paths:
      - dist/*.whl

git-inspector:
  stage: reports
  image: python:2.7.16-alpine3.8
  script: 
    - apk add git
    - git clone https://github.com/ejwa/gitinspector.git
    - cd gitinspector
    - python2 gitinspector.py --format=htmlembedded --file-types='py,md,tex,html,css,js' ../ > ../git.html
  artifacts:
    paths:
    - git.html

compile-report:
  stage: reports
  image: texlive/texlive:latest
  script:
    - cd docs
    - pdflatex -interaction=nonstopmode final-report.tex
    - biber final-report
    - pdflatex -file-line-error -interaction=nonstopmode -synctex=1 -output-format=pdf final-report.tex
    - exit
  artifacts:
    paths:
      - docs/final-report.pdf
  rules:
    - changes: 
      - "*.tex"
      - "**/*.tex"
